<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cqU3GoF' shared service.

return $this->privates['.service_locator.cqU3GoF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::form' => ['privates', '.service_locator.tUQnhFH', 'get_ServiceLocator_TUQnhFHService.php', true],
    'App\\Controller\\BlogController::index' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BlogController::show' => ['privates', '.service_locator.5aciI7K', 'get_ServiceLocator_5aciI7KService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\BlogController:form' => ['privates', '.service_locator.tUQnhFH', 'get_ServiceLocator_TUQnhFHService.php', true],
    'App\\Controller\\BlogController:index' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BlogController:show' => ['privates', '.service_locator.5aciI7K', 'get_ServiceLocator_5aciI7KService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\BlogController::form' => '?',
    'App\\Controller\\BlogController::index' => '?',
    'App\\Controller\\BlogController::show' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\BlogController:form' => '?',
    'App\\Controller\\BlogController:index' => '?',
    'App\\Controller\\BlogController:show' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
