<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Drv8Zty' shared service.

return $this->privates['.service_locator.Drv8Zty'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::creation' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\BlogController::index' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BlogController::show' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\BlogController:creation' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\BlogController:index' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BlogController:show' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
], [
    'App\\Controller\\BlogController::creation' => '?',
    'App\\Controller\\BlogController::index' => '?',
    'App\\Controller\\BlogController::show' => '?',
    'App\\Controller\\BlogController:creation' => '?',
    'App\\Controller\\BlogController:index' => '?',
    'App\\Controller\\BlogController:show' => '?',
]);
