<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDLAwJn2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDLAwJn2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDLAwJn2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDLAwJn2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDLAwJn2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DLAwJn2',
    'container.build_id' => 'bac08d27',
    'container.build_time' => 1561716776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDLAwJn2');
