<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNOc6vdA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNOc6vdA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNOc6vdA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNOc6vdA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNOc6vdA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NOc6vdA',
    'container.build_id' => '5b700640',
    'container.build_time' => 1562149338,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNOc6vdA');
